# Max values taken from Blacklight

require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 200
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'test/controllers/**/*'

Metrics/AbcSize:
  Max: 49
  Exclude:
    - 'app/helpers/form_input_helper.rb'
    - 'db/migrate/**/*'
    - 'test/system/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'app/indexers/document_indexer.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/migrate/**/*'
    - 'lib/tasks/geomg.rake'
    - 'lib/tasks/geomg/geomg_sidekiq.rake'

Metrics/ClassLength:
  Max: 169

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/ModuleLength:
  Exclude:
    - 'config/initializers/geomg/field_mappings_btaa.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'app/helpers/form_input_helper.rb'
    - 'config/initializers/geomg/field_mappings_btaa.rb'
    - 'db/migrate/**/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20200529173739_devise_invitable_add_to_users.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20200127213637_contains_association.kithe_engine.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/import.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/import.rb'
    - 'app/models/import_transition.rb'
    - 'db/migrate/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
