require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/geomg.rake'
    - 'lib/tasks/geomg/geomg_sidekiq.rake'
