# Max values taken from Blacklight

require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/bundle'
    - 'tmp/geoportal/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 200
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'test/**/*'

Metrics/AbcSize:
  Max: 49
  Exclude:
    - 'app/helpers/form_input_helper.rb'
    - 'test/system/**/*'

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'test/models/document_test.rb'
    - 'app/indexers/document_indexer.rb'
    - 'test/indexers/document_indexer_test.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'lib/tasks/geomg.rake'
    - 'lib/tasks/geomg/geomg_sidekiq.rake'

Metrics/ClassLength:
  Max: 169

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/ModuleLength:
  Exclude:
    - 'config/initializers/geomg/field_mappings_btaa.rb'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'app/helpers/form_input_helper.rb'
    - 'config/initializers/geomg/field_mappings_btaa.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/import.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/import.rb'
    - 'app/models/import_transition.rb'
    - 'app/models/document_transition.rb'

Style/ClassAndModuleChildren:
  Enabled: false
