require:
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 200
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'test/controllers/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/BlockLength:
  Exclude:
    - 'app/indexers/document_indexer.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/migrate/**/*'
    - 'lib/tasks/geomg.rake'
    - 'lib/tasks/geomg/geomg_sidekiq.rake'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20200529173739_devise_invitable_add_to_users.rb'

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20200127213637_contains_association.kithe_engine.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
