version: '3.1'

services:
  postgres:
    image: postgres:12
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: ${GEOMG_DB_PASSWORD}
      POSTGRES_USER: ${GEOMG_DB_USER}
      POSTGRES_MULTIPLE_DATABASES: geomg_development,geomg_test
    env_file:
      - ./.env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgresql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local
