version: '3.1'

services:
  postgres:
    image: postgres:12
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: ${GEOMG_DB_PASSWORD}
      POSTGRES_USER: ${GEOMG_DB_USER}
    #env_file:
    #  - ./.env.test
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgresql:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local
