version: '3.1'

services:
  postgres:
    image: postgres:12
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: geomg
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
