# Solr Field Mappings
#
# Vernacular => Solr Schema
FIELDS:
  :ACCESS_RIGHTS: 'dct_accessRights_sm'
  :ACCRUAL_METHOD: 'dct_accrualMethod_s'
  :ACCRUAL_PERIODICITY: 'dct_accrualPeriodicity_s'
  :ALT_TITLE: 'dct_alternativeTitle_sm'
  :B1G_CENTROID: 'b1g_centroid_ss'
  :B1G_CHILD_RECORD: 'b1g_child_record_b'
  :B1G_CODE: 'b1g_code_s'
  :B1G_DATE_ACCESSIONED: 'b1g_dateAccessioned_s'
  :B1G_DATE_RANGE: 'b1g_date_range_drsim'
  :B1G_DATE_RETIRED: 'b1g_dateRetired_s'
  :B1G_GENRE: 'b1g_genre_sm'
  :B1G_GEONAMES: 'b1g_geonames_sm'
  :B1G_IMAGE: 'b1g_image_ss'
  :B1G_KEYWORD: 'b1g_keyword_sm'
  :B1G_STATUS: 'b1g_status_s'
  :CREATOR: 'dc_creator_sm'
  :DESCRIPTION: 'dc_description_s'
  :FORMAT: 'dc_format_s'
  :GEOM: 'solr_geom'
  :IDENTIFIER: 'dc_identifier_s'
  :IS_PART_OF: 'dct_isPartOf_sm'
  :ISSUED: 'dct_issued_s'
  :LANGUAGE: 'dc_language_sm'
  :LAYER_GEOM_TYPE: 'layer_geom_type_s'
  :LAYER_ID: 'layer_id_s'
  :LAYER_SLUG: 'layer_slug_s'
  :PROVENANCE: 'dct_provenance_s'
  :PUBLISHER: 'dc_publisher_sm'
  :REFERENCES: 'dct_references_s'
  :RIGHTS: 'dc_rights_s'
  :SOURCE: 'dc_source_sm'
  :SPATIAL: 'dct_spatial_sm'
  :SUBJECT: 'dc_subject_sm'
  :SUPPRESSED: 'suppressed_b'
  :TEMPORAL: 'dct_temporal_sm'
  :TITLE: 'dc_title_s'
  :TYPE: 'dc_type_sm'
  :YEAR: 'solr_year_i'
