# Solr Field Mappings
#
# Vernacular => Solr Schema
FIELDS:
  :ACCESS_RIGHTS: 'dct_accessRights_s'
  :ALT_TITLE: 'dct_alternative_sm'
  :B1G_ACCESS: 'b1g_access_s'
  :B1G_ACCRUAL_METHOD: 'b1g_dct_accrualMethod_s'
  :B1G_ACCRUAL_PERIODICITY: 'b1g_dct_accrualPeriodicity_s'
  :B1G_CENTROID: 'dcat_centroid_ss' # @TODO: Rename to CENTROID
  :B1G_CHILD_RECORD: 'b1g_child_record_b'
  :B1G_CODE: 'b1g_code_s'
  :B1G_DATE_ACCESSIONED: 'b1g_dateAccessioned_sm'
  :B1G_DATE_RANGE: 'gbl_dateRange_drsim' # @TODO: Rename to DATE_RANGE
  :B1G_DATE_RETIRED: 'b1g_dateRetired_s'
  :B1G_GENRE: 'gbl_resourceClass_sm' # @TODO: Rename to RESOURCE_CLASS
  :B1G_GEONAMES: 'b1g_geonames_sm'
  :B1G_IMAGE: 'b1g_image_ss'
  :B1G_KEYWORD: 'dcat_keyword_sm' # @TODO Rename to KEYWORD
  :B1G_MEDIATOR: 'b1g_dct_mediator_sm' # @TODO: New field
  :B1G_STATUS: 'b1g_status_s'
  :CREATOR: 'dct_creator_sm'
  :DESCRIPTION: 'dct_description_sm'
  :FILE_FORMAT: 'dct_format_s' #GBL
  :FILE_SIZE: 'gbl_fileSize_s' # @TODO: New field
  :FORMAT: 'dct_format_s'
  :GEOM: 'locn_geometry' # @TODO: New Solr field name
  :GEOM_TYPE: 'gbl_resourceType_sm' # GBL
  :GEOREFERENCED: 'gbl_georeferenced_b' # @TODO: New field
  :IDENTIFIER: 'dct_identifier_sm'
  :IS_PART_OF: 'dct_isPartOf_sm'
  :IS_REPLACED_BY: 'dct_isReplacedBy_sm' # @TODO: New field
  :IS_VERSION_OF: 'dct_isVersionOf_sm' # @TODO: New field
  :ISSUED: 'dct_issued_s'
  :LANGUAGE: 'dct_language_sm'
  :LAYER_GEOM_TYPE: 'gbl_resourceType_sm' # @TODO: Rename to RESOURCE_TYPE
  :LAYER_ID: 'gbl_wxsIdentifier_s' # @TODO: Rename to WXS_IDENTIFIER
  :LAYER_MODIFIED: 'gbl_mdModified_dt'
  :LAYER_SLUG: 'geomg_id_s' # @TODO: Rename to ID
  :LICENSE: 'dct_license_sm' # @TODO: New field
  :MEMBER_OF: 'pcdm_memberOf_sm' # @TODO: New field
  :METADATA_VERSION: 'gbl_mdVersion_s' # @TODO: New assumed/hidden field
  :PART_OF: 'dct_isPartOf_sm' # GBL
  :PROVENANCE: 'schema_provider_s' # @TODO: Rename to SCHEMA_PROVIDER
  :PUBLISHER: 'dct_publisher_sm'
  :REFERENCES: 'dct_references_s'
  :RELATION: 'dct_relation_sm' # @TODO: New field
  :REPLACES: 'dct_replaces_sm' # @TODO: New field
  :RIGHTS: 'dct_rights_sm'
  :RIGHTS_HOLDER: 'dct_rightsHolder_sm' # @TODO: New field
  :SOURCE: 'dct_source_sm'
  :SPATIAL: 'dct_spatial_sm'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'  # GBL
  :SUBJECT: 'dct_subject_sm'
  :SUPPRESSED: 'gbl_suppressed_b'
  :TEMPORAL: 'dct_temporal_sm'
  :THEME: 'dcat_theme_sm' # @TODO: New field
  :TITLE: 'dct_title_s'
  :YEAR: 'gbl_indexYear_im'

# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

# ArcGIS Online Base URL
ARCGIS_BASE_URL: 'https://www.arcgis.com/home/webmap/viewer.html'

# Download path can be configured using this setting
#DOWNLOAD_PATH: "./tmp/cache/downloads"

# DEPRECATED Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# The bq boost value for spatial search matches within a bounding box
BBOX_WITHIN_BOOST: '10'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '2'

# Institution deployed at
INSTITUTION: 'BTAA'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'mods'
  - 'fgdc'
  - 'iso19139'
  - 'html'

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Use the geometry type for the data relations icon
USE_GEOM_FOR_RELATIONS_ICON: false

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'tms'
  - 'wfs'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

# WMS Parameters
WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
    DETECT_RETINA: true
    INDEX:
      DEFAULT: &default
        color: "#1eb300"
        weight: "1"
        radius: "4"
      UNAVAILABLE:
        <<: *default
        color: "#b3001e"
      SELECTED:
        <<: *default
        color: "#006bde"
  VIEWERS:
    WMS:
      <<: *opacity_control
    TILEDMAPLAYER:
      <<: *opacity_control
    FEATURELAYER:
      <<: *opacity_control
    DYNAMICMAPLAYER:
      <<: *opacity_control
    IMAGEMAPLAYER:
      <<: *opacity_control

# Toggle the help text feature that offers users context
HELP_TEXT:
  viewer_protocol:
      - 'dynamic_map_layer'
      - 'feature_layer'
      - 'iiif'
      - 'iiif_manifest'
      - 'image_map_layer'
      - 'index_map'
      - 'tiled_map_layer'
      - 'wms'
      - 'tms'
      - 'oembed'
